# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: publish to Maven

on:
  workflow_dispatch:
#   release:
#     types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 17
        server-id: sonatype
        server-username: ${{ secrets.MAVEN_SONATYPE_USERNAME }}
        server-password: ${{ secrets.MAVEN_SONATYPE_PASSWORD }}
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        
    - name: Publish to Maven Central
      run: mvn clean deploy
        
    - name: Release on nexus
      uses: monkeyWie/maven-nexus-release@v1.0.0
      with:
        maven-repo-server-username: ${{ secrets.MAVEN_SONATYPE_USERNAME }}
        maven-repo-server-password: ${{ secrets.MAVEN_SONATYPE_PASSWORD }}
